apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iOBGOa4n8yqgx5EvARhwV2qKzYcO2DQx48bZJVf88sHLBM9bQ0Bttuu6nVlU74+2147QHqQck1SwIFrXnsi3Vn8BFV+W3b/WVTreUdvtZZL7QiYVCAUJY2J8yID2tmvC7iDkmrhq/K7cgI1TSrVfis75wRHDdhetpNJGM0dyG0o2VuVfind2xv4CtgdXuZuA+M1mHHvVhTdxS5bWVaBsBCruK80qYa60IzBvc4Pl6jqwg3/jLDZrfPHQr+jVnKfL9Nk0xT5hoxEeLwDdhf8XXSWXwRNoIesiJQzffrUmDZ1zPFINlxXyjJ/8xCp2mj+fDG8ATbcAF8dN7eSNAthLK+U1WzXGr5vQLD6cl3CUc6j8a6Lp5+1pJskOIi/3ehG+,iv:O21DYB4UaMTh/sppu71IprrfQqqNKAP8qa7LAz467E4=,tag:pirKb2S0NQe1TItn7FQW5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:w4PAE+1i6jitWAwfOUqAR23QO7tFxhivlN7j/gTxuHIO7g1MrqEz3gmNlRnMY8127ObwhgxrwjskAYoN5OIy+GNkR9bwh/yWE7zoRzwVKzqMiEhlSJc/aMbx957ohszqxZdd9G1SCpvPBiynljQORDO++gks4LL1T/NK9Zs6/9BJqwUhg+uhQ4zF/q9BOTQPkThvG6IebEmdGPUX2ChTcj94I+axDOcvbRtgiYTRIc5XwTo7MKlE+1kzl5prKeH787bOL8ZYQGLLYssVrA==,iv:KK8m1Z98aiG6Cb3LMcdTrDoC7x1e+taeux8H3wAO9d8=,tag:1SkEzBAns9IWCKuLqQyV9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Mmc0c/qGcRAupxSE+9JNw9yNkh+EEDzs0bHN/akDOI+JQ7Cc6tutZ2DSFHz6/2T2UVQv+GE5yVAapDIq9PHJPNhAnXXyZvfRoY4WWbiUd0ieQwmadEJ2aC+rZDMbTrSRkPo3xE7PK4hLoaC+41IKyJiBN1Jn+AW0XmlhmDmqUb9RVEFrjtWKr9aQ8BdxhSUsgyAIDURd577W2B9ePcDCI6lfQ+7Dkf1V6wOF,iv:lXWYMKibsaCAOloj+ynIfsgQkgBrP6LvTbxB1Yunb/0=,tag:Si+lMzD3nXp+RTQxP7j+0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvemE1dTZhd0JJanZuQy9N
            OGxMTmpiN2dnL1JDNlQxVGQxZHYwU0VkT1ZBCjV1N1YrcUxsekd5TlJlUmViNFkv
            em9KV1ZOUW56eFlvR3RtZDJCQXIrblkKLS0tIHA1YTZVRlZSakVneUl6M3JNdGtU
            ZlN1WkFLUkI0YWhFZy9yZVVsSGtiQWMKOmSuhVUgAWJC6slV5/TiUprnf2PlyQjp
            V+rFswMZP1xoWF0RWF9kSRrBibPLI/Ymorel7j/hdluwgEbkAJF3Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T23:16:30Z"
    mac: ENC[AES256_GCM,data:dTvhRSI2aS5/RboMFwzqZ9Qvc6/ZS73ysEH10LRFl3CzicLJ4orQscDU89cmPdSyqJRI8jg9cCGecCfc4VQ2aZ5uhyumvyi7JVMItEKAaCB3KEG4U54St1c/gpF8wzr5yIKlG5mZyxRIVdjhmA2Qqf3U76nFMVEDswl5uvgyAIg=,iv:HNbsPC56QzAgxZMSBn3iiqpUBwvmnSFaslI/WKnrorQ=,tag:AGknhpzUKu3q7BPUTWXhtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
