apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0E0Is+EfXZbwB+GhpTIlmguMv1WFxg97TE7O8hYdqRTc1b6+uPoG0g0t08I1WLtkxfxo2yp6O3ixLQaaWbK4n2z35Kj4O+2W8oc2rbo9iqPcJe15iYjye0n9nNN/6kWkKYNzz0+OEmPy3H1jTFCN0THPCJ4r4BLgU0joPWaxRKKRyNZ10wEcTtp6r5+Y9cEiWCTN8wSkbxBwrooS0gmXTjX53jDKF45F7E90fUetcOXpBFB9DP45smeddFWkHiZYR8yBoNlTs9VSnMOI/qNRZUc8KLJDJzm582yoD9ifecYYpgBz+yJ270gDVw77HvY50PachwHMijwmIWEko6GteukcbpwZHKFrxpPwjgDkzdbeN+PkL/BfJ276ni/fHnrm,iv:egkFgjJ+Xlbeny+WwcI0iPsDcfrYoN/+NCm2iHDDkhs=,tag:qzeo260EkxH391xHNrNdQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:AL69a0oS5wCUmkV6IGH/Tu6mdF5AGO8hF4zh5kvo7CLo2Z2fyoLerXGp1lLdsMo/gWW8aCBwVnNoePhzDHqNpfOTlVIJT4IfGYrLRyBSNR9EA4m609WIYZbXogvqogK9gB/wNd0ciszyjkdYKo95KD2BvaN3GxSFq/u85blpVmf/xHskYlWDzFg+9Ju3RjcJQSoOORQo6sOJB+hqvB5wTDgyDz9JijeHDd+c/Oq2YTmR2oBBMvVQ//Y6yZqHTxRsg/ayAWqjpUBWlBYU5w==,iv:Z2yk5rbD6YscCDGsTiWo5lg1B/7ZfmsdE4W1ZrxbOLw=,tag:hcQcysAVo8UIS99LeUo8sA==,type:str]
    known_hosts: ENC[AES256_GCM,data:OlUYSLY7P9X2cGJl9KAj/ZkqLF0fgokEjDeYh0jhL6wJXDoR9bEuJejpYTArdEYBTt1udIL44ahWh3+LG5UTJNWCoPA8q74/bFAO2MIPC0TmiR8+5p/vjB72uwqwt8jjgoeoZRkt13japQMcb7kICWlV0ZrTkbjPeHbw9mIQvPekdyc9UnphPlznAtHQRC26jWqcwDaF0SNckyLGsh2wCuRvd2bzF0BvVQoY,iv:FZa+vvrtmHtQZnYJKTsO51z0/08HZ5+fElKbeG+t1w8=,tag:ol2HBdWEDp3drsqey/8CSQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckxMdDUzNVlsYngveDZr
            SWlHaEVTRS9oSCtmd1R5Uk9HOTNnWnowZ1F3CmxCZGptVG83emUxSVA0TjQyZVFn
            dVBjQ2kvVG54M1JzM1dTSitFY25LMUUKLS0tICtPUzVhdGRleElKbWpyVWxGanA4
            UnJ5dEdlOGtIWWwvOUZWUkZQTUJFS2sK7/5RWcjsdKLax62HKTI9v/Zg2xjD68E4
            +2JxhtbXPY7mjoQ8Bq7RJiuq42Evwz+OchzzJbKnAdU3hn300INV0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T23:38:41Z"
    mac: ENC[AES256_GCM,data:nUi5GMIAdRJ3xrc4c2U5AfsRSOL/bdToQjH++lg/FOYWKqxUHeKk8Zp+HBQN/YwLLBQo/HUpTBgSTT0dfL9F0eRCOGE6yFhR+C63dQ71WNVzdRyb5T2SLdqTKcIp/dVdahk3WwjTrNMJcg03FG77yZn1X0aHyPoMLDqZpSyGUfQ=,iv:pyQz6CwA/ycd0rbgDtdZ0R83W/bSUJ4dl0LrVRqeUfE=,tag:ZtuHDdYeYlM/Jbm3y57Q7Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
