apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9WDrRj/s3OgCff4Yq9L1GWKC7bnqGrjdKB/5ZrQuXiuf7Ms/kBA5tpQkindx0ie1+25owLH3kxmjOomGmcuvb9geJIjJNyC0dBjuiCMnyF7lx9YPOrf0WYpIzW4vg8UNKaUQpfF1tWs70AbHg/MjgdSgXkVpoMbcp5Z4TpVmjVFzoTOdXDwz45tU46hsIkbdHMxRjV5Hbe3hILoWB1P5iGnhdv3H6nErX/jUm2/PKhPYW00jGBFSxwEt4XG/7kQmR1jToRgKledHlgPNU9Z8S0VieeFokjHGMW2qzo4gK9K7Iqr1RSDCCLFYk/ekiHShCeuefOGNm4qtrw/lNGWkF5eA/MwOandFV8+JDP9kC+f4RFAoaa03aEmGnXWVPQeS,iv:bUaEh28j3HuLHw7l2dyy3pbslY+wKhNKg/2PN2FIFnE=,tag:xWqqrzzCD+d0qWPp2U8Rxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:bfxpNXv18v7fl5CM72ygOYMh7uW9n35cFEmfsNTjcE33yQ61vQVvZNfchEe0MI8fiGru4YXlXSWoNKkxa9hhrWHnCbxfJ+qWgA5nBA/u78+fXZ/4K23oqzhKNu8hnrXNhsyxYL6bHSJnOnvn20+WnR7fbpoGLXG2qO9Vgag1UBauvB10Bcmgdpgt2hHs+7GOkug0Q3ZFxl+EY0ZeemIBrmcDbt+vXuCh1wrNpuLUKbLE1dZLMjdlRqPONavBJavoHz0NnSAruTmGhDeiTA==,iv:FdKoWe1LZGcO7+nm07OCm+ZRkaza59MhNTXhs1cZhG8=,tag:NO0mN+9cZSiKaPjts2CjnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Vgg/v62+O9VQg+ofzkHcNTL5Ddm1Z2HtWvcBbhIRUfCsqzw2EEuZiC+0oxpVyHlZ3/M2ucqkkW6tRECKSkX309XgcVWqwxU+X2qWL6ncnIk1/OHq7PW0fp+DKhIhiNUxlY9jfEpXArrxK1vTKgfuhOXxrZfe4VTHDOWmOBTiFTlRQt0hNZRhh0qea6xnIeN4WeilLtFa53zJs1lmMoi+/zVJ+EpeC0qsMg8a,iv:I9VDv9HWb0gA2pj2OywmZLkkLbX1ETWUfQLxzbC07sA=,tag:CBtYqyRiSNWDDxy6+qieqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTBZUXNNL0FnNGJkZnRY
            VW1ZVXo4MnliSUtzTDlEek5ERUQwZVJVRkVVCjZuQ3R2UTY5K1N4NzhjaGN1dGUy
            MnlXT1RlUUpGeDJBb01YYXBaWXRVYjQKLS0tIDR6NnNiV2preVRXeCsxaTJTa05k
            aWVMdHF6QysvM25Za2hOanFiYVU0RW8KKUiqKnbSy7KpVeboCpaQ3610RwOMzhDp
            DoVxf17vyXGgFn8KI54RWbTtMXlCInI1z6nDltRfrq2noeJrnO8mrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T05:06:18Z"
    mac: ENC[AES256_GCM,data:FCk6eihjBGuNUAOpaxksVXjFsvP9eafxUJjbL0VH5im2cjZXoHQKLXXVhCiuyWdJNi6qZHl6pgHhNgC8k0fvzQ1+LpDIv1V613ug2SOh2fOwgke2jYVDSOGoeS4YlbmzC7RGzqG1d/JAC6JGuZNlXHe/WeilPn71uMkqu1vvOY8=,iv:we2XtsgOOWI27midFvPK9B2+Oac+UwEYgUvdZKkxNL4=,tag:5PcY3Luvzl7po3iohucFlA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
