apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ujpvTfmqjMW8xxgPCXWLs9OqBf0tLuXiGkix/bgKUL2Nt4rp3rshzpCk4SvoixRMrgMB4eSVhPcqhY3hUgvZsBXkoxoltecGW6IudC40qfKmOS8Nm80t6Jg5dqeHBXu/kXaUn7IePussoSCo6cA4lPQxPN1AjM6OpE5FFtAJVANKl7++TwzSFxvJ+5/Wemd/BIKRPPPj3HkQmnpsz3nIRPM3pIPFp1DTIPhjgKWv0RF4HxLBujxglEy9n9rjkXarcVRx382meBSCfh9pXBCzUSOsXTgyZq3WshR3CytK8PYD2GkSaF8cevkllyegVs4g7+1kz3oEjLwmws++dL8aUvPg3Xvz6Zw1pdyPKobhDTmf3lHKu9geJsth/MKUeN0f,iv:df08bLhiCOx75Mtx5t0dWryaUx44PPKMMJTxSF5q2mE=,tag:CLxvIpNR/x4/blXQb9219A==,type:str]
    identity.pub: ENC[AES256_GCM,data:K7MkdcaUG2Ij+vKratSTEOtQK+0JqwR1UlBLsNM48vaF4F6XY8as0E67aX/F+z3NccUnGvnEazajZaTEWMn5+tbX5hwgYwuJxdXX4EB10waJp219r7V/p/stlS5ZgRMoXUf1wYSzGWw8iNY+5hySw1nhDgqZ32+D8B1ibvnq3IaEFyaEfuZMiO95uNAE8KWi5Ec3K+2UhM9+ThQVKVj3KR60VM/il3rV/AC4FMv711hGaRWtO33i5GJS31UTlvrxLsno9f7Lwmpv7EUseA==,iv:s2mlnuiQlQ9C9iLBzNZw/7HeiiAWdkCBNl5go4B04Rk=,tag:8UygkFNbevYtXBRFxvcS4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:H75C+eXx8tdhAHGNy69ZGWkNiS/N6SSurPb65jSHPaLbUFFEA8tnw6oDRYgSLSNxpcMCMUT0N7TeCfmpUXxEju+6FqlASQ5UfdJq4iMcXYDw1K5V3pxCpgc8p+IXpqV7ZIO9a//aM32BeXyNVM6DMSSP2+DGFMV+bGyoV/Oufv/iNQ6UhDH54GYwByyXiMKBOgLRwrAmmORUX5HFYsImMKdKOLvN4pLCeJEU,iv:6HuXZWHo9Ry/s+DvosnymO56JLnE/9xIbxx44nlx1ZY=,tag:b1LgVkaiNmxO0zttq/TfJg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUHErcHIyeUtpamdNQnlD
            bVY1azRKUWZydno3cW13UlMrOTBYcGc2VEI4CkxGT3hWY3h1SUpZNjJybHVESjE4
            QVZ6MHN3SHRTZWZQZjRYcWp0dEd4aFkKLS0tIEsyTld2OU4zMFJMS3NCYXZVUHo1
            d2U5SXhjM2VkUlI3QTdkV25OMDhDTFkK8TUl7M5DW5frjOSdCm4np5OwqpJUlxs+
            HCqCqBEuBIKwycgnYdQQVh03O4uSB0XMsOx7zjwHXD6UJYnzKbqD3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T06:42:18Z"
    mac: ENC[AES256_GCM,data:t1rSygmamWXUXx2UbYZdORjNHvBowzy9drkm24ES6y8othXgn92OSLz5SA7AbqlpGuzAoYYHfqniilTI9puZg3nqeXnoQJj45THbLuJ0FPMAR+uYqA3mVkVnVyGETBIUje+2wlPZCW8jtSiYcj734fzYTgm/OwKGwJuUzi9Uvq0=,iv:SXkvN1MPA7pFKUsjoUBBYlivsa8e9ITVXiDMgDVsV0A=,tag:odgcA/QlLxxQhg42mY+bOQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
