apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IFDJPlF0wyUVWIYItbA22Tiax2dhG2sUYjWDkxH/4RUIGZiimbtzk7GTJW2W9R4KvAdeV2WpNpGILp2QuOvlh409MFeRCUY4E/S1O050phY4RRg92fQccsX3hHLYBRL9P55/ooQNp2u47EwWXVDQmX8QeEQAGGX2vKLW0p2k27FFpd1aywTToWrJwgBLX2TIVt32mbBJD1jmIHeL4dEgPWNlUO5HROkQlECz12zonPMzTvKkM+qzTS4fRVmZLATQtZP/i3CJ7tvyei7p8dsJa1YDqrH7B7sWeYaZJ3VYEkCCfdvp16nTEUQQatycHo27yiPUU7qR4rHAZ3UefX92hMNXlww0/qdfWnCut+az9PWaSB6uuq+cCd0R3Z8D1yAk,iv:bVvffSBPIuH/kzhFX/GIMbRp25ikWBbPbhUp88gg5kU=,tag:asTAsX9DvEGp7LgAVLYgOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ACKmzFZxjyPTlT1WabH+qeQpFpgZmcR7KyyeOl2maNi2ELnlvZ82v58YngoUo3E5nM+UsTvLUZuWBzHqnn/BvFzHhNOZ59X4h2fv2j2pVqh8/5jEz5QisBJhKa9s52shPHQYNxXFLTSVOJUZ75q+gK0IsactOqndCj+O9ceOWHRj2BYUYcBhZ0W3r8EGuupUmGG7g5D+LM2wpPSgtsuIRh8GKPG1BPi6KjJ4/XCGarugMrc8va9nOLY6tdb3K2r8waET9f7qevShV60Hzg==,iv:3MZ8E5udgm3yz/2Uqq71jjupyo/DPC8Qpw/Ce5z0Sqc=,tag:hBHCytUIf/c0ybTrLya3OQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:WnMWk6u0SzoQ7RBrOh4GiNyl74M630CJeJvCMRLBxkIABqKAJBwyhmLs1xFD6sLzfGxr5vbZXKYGybmPeHP+iwKF2ARHdw7izK3NXJXao9WxbMmx8KQsLHcLak7ye4vTnweYCFxWsKS2pUkbfC+TSZi5ZdO7MuZoYMkNn6LhNMrSHs+DNIhPVQsXQaqJ6FKSUIgmeHC7AGqhAjoirwXdKZLV8y40BbfIFSvy,iv:vLJRHPxhi3rApl2lxyBXq5CadtgjAH0+QGhzhNflfYA=,tag:2Cu/DIE8jrxbP13c0c7ZjA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkprT1hYbmIzSzdlUUIw
            RGxXYnRsaHFRekYyczlGM29ncExkV2F5MDBJCmVyVzlMQVVIM1Fic2t0dTY5ajRt
            cHNZZTBtUjhzeDArTFFQTDhLalo3WGsKLS0tIFBDZ0lUQ1JJelI1bUJRRmE2eWZU
            bjM4LzR2UjZiMVZIMXlSQjQ0QysrRTQKSkSq5kXEeY54USYLIPmmD8Wcy4dxn/AP
            7rRhd/O8vc62/DpIsg3fOOhCFLpdHgRwC6ZSg32JneH8tde9tXxU0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T00:21:06Z"
    mac: ENC[AES256_GCM,data:86u13jA5yuWTp6vnm+kIwwNtcjy1W4sg9pstm+p5m4G6f1xqZq1e0AmQEqnNKSWcZ+tEDvO4aGjLsV9IH+lTwakGhe40xYWl2itOOVNcUAwV50qhXpU9sxmgbJtZw933WqrT9HqIEfWqs+0JsH8ne1qEkg+04SNDyvVTivkBQK8=,iv:LWfFyFnhZWXREAaMhZ6X8QDkEGrVt404Uj6gVIea56Y=,tag:ETnq97X0wU16buJPkhvV6A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
