apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FzHg/0yqWLTDF+5aHdhWSrBssYAU6q47RBgIZIorlOE7O1v3EGhlOgR986g0McVakv0ArEfJd9nzCw8YtQ/TzKI37j0ukwAce7cZ0k1KQmyim3gRJK3j1xp7p5INl10ixSY3tcjeF3Jw2tVR0KxB8nmBJQop/+VpmGiwlMesqntLZ/PoV7ozIUCqbE+RUmIddAoZRdEqqFbC0/d7Jghf5PoJQZaTt9E5+IyiqYLFS4hMf5c+D4DocizYlH2X4feHf2XvP0AqrEGiXMo1hfDvFJNxW/rPzyIqDWPOC/Uj2tP4QsRfEaQNGxytO2DAhdOOUvr1Bx52BY1VOAsgnN+/oX4nHsyp922Y37h6ALjTZTqI0gxuQVfZPklO8AS9F1nf,iv:+iJVCqd72tIk0lg9MUzTZEuPz5WnLCmr2PSa9BI7rA8=,tag:XQQ4DAWImTGIf+SrzKsm4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pq7hHfL5jNdB6+Yat95NPaNVb9U0AWuQ/cqWBbEao26ZLlSF3hVDHjyyAjlAwkqLfnCqLrn5sdu+9rBS2qQth9XsDu4VS4QsuPWRJ0SM6hVaDU4R/cv/7FyheYRBvL9WUNZHGWz2m/tzlNIrcSp37r+DKZ6Fr9Y+vL+fksQuONlx+rSEOu6/7NUHm4ULFy6JLd0VCRbijB+S2KW0Dqe1L602uXn4bRwot809D2Ucwneo1k5nE4hLYnb/DnXFGan1NlYlSVQaMNi21bUiMA==,iv:zTtxX9zdT6Xg+QIZ6QIiU+56y0x4YRVph8bHni5oQvs=,tag:d9jRUA99s6xi3HVEl54x+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:m0LzNIr4bOLnbB+LFf6U5yzODng6WhztTD1ueyEC88kyy81jD18iAxwF3RRmuaabqVGv04Dun+YVTZTXkx6eauhlKKWWjIXKSkZ9XK//u4NOY0qMBMSUMaQdVIPpc+JmVHKvuXJM1vd3a/rqj8fJH1e93axP3hT+eSoxieb1igP0aD/itRLj7TsN3rUv5ZcDAhi2pojcGbFAeTxL1cH4l3aY5c24CitIDWzi,iv:KSjuEt8ifKm+Xl1WvzCT43EqzXOba8zqMUMNOraA9U0=,tag:xFHKQR3Mxhz/xQka8SNlGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMDdXdGJmNlJUbWg1Q2xX
            WllXVUcxc0dxUThOWnNBWk56Yk90QVRlN1dFCk0wYXA0S0ZGVFV2WUU0REg3RCth
            UDVTMktRZm9rUE5URFN2VmxuM0lmZnMKLS0tIGNtRXhuZjJXUUFFc010aVVVQXJx
            aFdEZVFGRE1jZXBjTXhGejBYT2M4NlEKMFibOhQwJjX2K5gNzJZVnddsigoV87P6
            tEkh/N9dptbdE6BwSy9FTypnGITPA/gqZdgQGc0KAN5Hl464/m9GMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T03:55:09Z"
    mac: ENC[AES256_GCM,data:86tq4Boi8PWQYylD4revuStuUVEH0LHcacXAtjlSq9Tb8fJ1C2RDb4f+TVV6Ao69+kfb/UBXVu7rI/CNbHX8yE9Z1zG+/9Pflgxc8Jkye499mkj9AW1BBIdGZAF7QCd/D+FIbccnoY8SAzeTsERAqxcAEVrskMwxqXUkTs5DmvA=,iv:6xGqU/E/tP2UOeLO1sBrRUOV4cbcpee0BGcOgXOX6V4=,tag:wMkX03zFVn28Vf1Zs7ufdg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
