apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:29UvbRS5yAoHjID2nh6TM04FkzOT63BuNNmHK3ZdFMwUSsWEQcXU0XZSAeC/el5K0mTx2pjfUyr3w65TJ9lEwgUYd7XAfStDqriFnmrChvF3h9/nuBgWmuch++i7kE4KRjy6rXEjHnRKzfQRPcYtiG3DOscisBo9ARlUmBQZdI6y5iI48Y7rjYo00Ehg75DeTUvnjg+Mmj9cI0BWK7RR2tuq2Vor1qPKyrr0EOqzZyRNEQLcPd1CK9hk1UPorAL+niPf9uyf8smDWVjcXnmmX44cXXdoW+e6/5w/TOlTZyXmXwKhqYnvWpUnTjqV3XYEBogcFiWQccFlgqd+AkLCwnh3HoqQd8yQHhT0yRQp4QJIKoyXOGDGtM6bKN7NOFrW,iv:yuub7oxUWfTdoMWq488ExX37ZhCYxawhJrifH82nmdI=,tag:9Vit9Hc7Xzu0aHpS9y4QEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:rYVKYRN8nct2d+TlNNK+7reKEOE67/jaDBdE3DYtt0E0p8a41ND61wp3rSyIO7w73yf7IonDZnSBwV+8IrsFD0ASh/fUjfEKdXquQQH73AJlMU/gRlW8B1mT3PoHjwIUzhMb9pmOSNWbPyvNRG1X2iEoSPAIk0qz7reBgDz4XRb7AS/VHV6K8QWNLvGhzj9JCR3EQ2sceSNrXT6l7QqvIAM7eqz27LhjojdeTM3cUOh88EKvb7e/a+16ilXANp1ffYDPXips8SvpJpeNoA==,iv:JcnWFYkbyf6zjjKl8AoGUTSO4go/kK/WFWH0tCrbVKE=,tag:mrbCx1jInfcyE6gb6/sW6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:fBcBaaDpm4JQgd4/qQLi9iiN5NcLdcDG1PxyKxrDJK58E4whsPhUNV3yP8VAFA6DhBV8mWPtGV0HilgdhG1zN/n8g7aKfTGmU/d+xF4hrtIKCbIG9VgjPxIWLA8xH++rCN/AFEz0WOEoOzaiXbpJ9AuvimTg/Xn84gWH1mD+6w2EWpMQS2o5nUNB4iKgjZm8PsvVCE16cleYD6X2NhRkOrjKjKyKBSsZIk2+,iv:lQvR7E9IswqfTRvTtCt2A2ZQm0XmAma1iTJJqT5AVSw=,tag:fxwfaV8pe49gVV1K85tvig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jheaa450llplqz9ru8qldf02mufy7n8tedpdyuc9x954dpm2swsl9e7wd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajhBSzhYVGs2TkhHeDFn
            eGV4Q2ZWMno0WmVTeVROUlNlanV2bFJsalYwClBuYkZxYS9VMnNMRktNbzNOZUhV
            cldGQldOYTdNZnlpVHM3azNtR3hwRVEKLS0tIDlhWU45YnVDQmRZdThTYVl4V204
            RmJOUit2T1RsUjJDakJYRjhtOWx3aWcKbQjVqLczepXwOSRGPtF4qwq9aMGHHIgH
            mPrGRgbwsdeXPx9L5+kDoC2kPayK4CYRcBYXHlnTVCgbzZOfcQaTtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T04:37:25Z"
    mac: ENC[AES256_GCM,data:eyE4c8mt0vaLmErw1jJfiQWuW4Iv6wCG496SRq8pGNR+uF5I8hm2ipr2eYTAWDbvDWP7TNCeM71dhMiZiNNDpSXTVVPLfX19nL5tJ19FPxwzrLfFnAxLJATi5UtxqIHs7wK1aNzmx+FwROwQLIs2BmQ4JdOVnxka3ecrKFWzytI=,iv:1VC4M+21h532CcmzUiJXq8/fZl2n/U5P7L4LPn1aIto=,tag:hlJxLljG9Zn3lam7Sc/SKg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
