apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: librespeed
    namespace: librespeed
spec:
    interval: 15m
    chart:
        spec:
            chart: librespeed
            version: 14.0.14
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system

    values:
        # credentials:
        #     backblaze:
        #         type: s3
        #         url: "${BACKBLAZE_ENDPOINT}"
        #         bucket: "${BACKBLAZE_TC_BUCKET}"
        #         accessKey: "${BACKBLAZE_ACCESS_KEY}"
        #         encrKey: "${BACKBLAZE_ENC_KEY}"
        #         secretKey: "${BACKBLAZE_SECRET_KEY}"

        credentials:
            backblaze:
                type: s3
                url: ${BACKBLAZE_ENDPOINT}
                bucket: ${BACKBLAZE_TC_BUCKET}
                accessKey: ${BACKBLAZE_ACCESS_KEY}
                secretKey: ${BACKBLAZE_SECRET_KEY}
                encrKey: ${BACKBLAZE_ENCRYPTION_KEY}

        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: speed.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix

        service:
            main:
                ports:
                    main:
                        port: 10016
                        targetPort: 80
                type: LoadBalancer
                loadBalancerIP: 192.168.1.245
