apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: librespeed
    namespace: librespeed
spec:
    interval: 15m
    chart:
        spec:
            chart: librespeed
            version: 14.0.14
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: librespeed
    values:
        TZ: Europe/Rome
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: ${BACKBLAZE_ACCESS_KEY}
                bucket: ${BACKBLAZE_TC_BUCKET}
                encrKey: ${BACKBLAZE_ENC_KEY}
                name: backblaze
                path: ""
                secretKey: ${BACKBLAZE_SECRET_KEY}
                type: s3
                url: ${BACKBLAZE_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: speed.$(DOMAIN_0)
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
        release_name: librespeed
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10016
                        targetPort: 80
                type: LoadBalancer
                loadBalancerIP: 192.168.1.245
        workload:
            main:
                podSpec:
                    containers:
                        main: {}
                replicas: 1
                type: Deployment
